language: java

jdk:
  - openjdk8

# whitelist
branches:
  only:
    - master

script:
  - ./mvnw clean install -Dgpg.skip

after_success:
  - ./mvnw clean test -Dgpg.skip
  - ./mvnw license:check -Dgpg.skip
