language: java
env:
  global:
    - MAVEN_OPTS="-Dgpg.skip"

jdk:
  - openjdk8

# whitelist
branches:
  only:
    - master

install:
  - ./mvnw clean install

after_success:
  - ./mvnw clean test
  - ./mvnw license:check
